### ISSUE TITLE
Panmatrix

### ISSUE THREAD

**Issue by iferres** [kloetzl/pangenomesim#1]
Hi, I'm using the reference guided version (I'm Gregorio Iraola's student, I think you two were mailing each other a couple of weeks ago), and I think it would be quite useful to add a panmatrix (presence/absence) as another output file. I suppose I can get all the information I need from the `alignment.maf` file, but if you plan to continue developing pangenomesim it would be nice to enhance it with that option.
Very good piece of software, by the way.
Regards, 
Ignacio

**Comment by kloetzl** [comment]
Hi Ignacio, glad that you like pangenomesim.

Could you specify the output more precisely? What are the rows, columns and entries of this matrix? Maybe you have an example ready.

**Comment by iferres** [comment]
In a panmatrix rows are organisms/genomes, and columns are genes (the opposite is also ok). Each cell has ethier a 1 or a 0, meaning that each genome (row) has or has not that gene.

**Comment by kloetzl** [comment]
Fixed in e4fb04d. Hope it is to your liking.

**Comment by iferres** [comment]
Great, thanks! 
Regards,
Ignacio
