### ISSUE TITLE
Bug on reference guided branch

### ISSUE THREAD

**Issue by iferres** [kloetzl/pangenomesim#2]
Hi, me again. 

There seems to be an issue when it samples genes from the reference. It does great most of the time, but at the end of the genome files (and on the `alignment.maf` file) there are a few simulated genes (all this of length 100, which I think is the default gene length when you don't use the reference). I thought it could be running out of genes from the reference, but I checked that and this is not the case. My reference has 7000+ genes and the simulation took only ~700. For instance, a simulated genome with 401 sequences took 339  from the reference and 62 were simulated. I simulated 10 genomes, theta = 100, rho=1, mut-rate=1e-4, and the reference, as I said before, has more than 7000 genes.

Another bug is that the panmatrix seems to be truncated in most cases I try. It only prints a few rows, and not the total number of genomes I set.

I will still continue working with the software as is, I just want to report you this issues I found testing `pangenomesim`. 

Regards,
Ignacio

**Comment by kloetzl** [comment]
Thanks for reporting, I will look into this.

**Comment by kloetzl** [comment]
I just realised there are some serious logic flaws w.r.t. high rhos. Basically genes that die are a problem. :S

**Comment by kloetzl** [comment]
So I just pushed a big commit that rewrites a good chunk of the program. It *should* fix the major issues of genes getting lost in nirvana. Note that this change has not yet been merged into the reference branch.

I would be very grateful if you could test the new version and reopen this issue with any follow-up problems you find.

**Comment by iferres** [comment]
Great! I'll report you any new issue I find. Please let me know if you merge this changes to the reference branch anytime in the future.
I appreciate your effort.
Regards
